---
- hosts: all
  become: yes
  tasks:
  - package:
      name: httpd
      state: present
    when: ansible_distribution == "CentOS"
  - package:
      name: apache2
      state: present 
    when: ansible_distribution  == "Ubuntu"
