---
- name: installing package and starting services
  hosts: all
  become: yes
  tasks:
    - name: installing package
      package: 
        name: httpd
        state: present
    - name: starting service
      service:
        name:  httpd
        state: started
