---
- name: Install packages
  hosts: all
  become: yes
  tasks:
    - name: install all below packages    
      package:
        name:
        - tmux
        - rsync
        - zsh
        - wget
        state: present
