---
- name: mount nfs volume on linux
  hosts: client
  become: yes  
  tasks:
    - name: Create nfs directory
      ansible.builtin.file:
        path: /home/nfsshare
        owner: root
        group: root
        mode: '0755'
        state: directory
    - name: mount nfs share  
      mount:
        src: 192.168.64.8:/home/nfsshare
        path: /home/nfsshare
        opts: rw,sync,hard
        state: mounted
        fstype: nfs
